PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY);
INSERT INTO grdb_migrations VALUES('v1');
INSERT INTO grdb_migrations VALUES('v2');
INSERT INTO grdb_migrations VALUES('v3');
INSERT INTO grdb_migrations VALUES('v4');
INSERT INTO grdb_migrations VALUES('v5');
INSERT INTO grdb_migrations VALUES('v6');
INSERT INTO grdb_migrations VALUES('v7');
INSERT INTO grdb_migrations VALUES('v8');
INSERT INTO grdb_migrations VALUES('v9');
INSERT INTO grdb_migrations VALUES('v10');
INSERT INTO grdb_migrations VALUES('v11');
INSERT INTO grdb_migrations VALUES('v12');
INSERT INTO grdb_migrations VALUES('v13');
INSERT INTO grdb_migrations VALUES('v14');
INSERT INTO grdb_migrations VALUES('v15-device-registry');
INSERT INTO grdb_migrations VALUES('v16-paired-device-peripheral');
INSERT INTO grdb_migrations VALUES('v17-lab-book');
INSERT INTO grdb_migrations VALUES('v18-sleep-motion-state');
INSERT INTO grdb_migrations VALUES('v19-step-activity-class');
INSERT INTO grdb_migrations VALUES('v20-journal-numeric');
INSERT INTO grdb_migrations VALUES('v21-sleep-state-sample');
INSERT INTO grdb_migrations VALUES('v22-live-session');
INSERT INTO grdb_migrations VALUES('v23-daily-spo2-raw');
INSERT INTO grdb_migrations VALUES('v24-rr-seq');
INSERT INTO grdb_migrations VALUES('v25-oura-raw');
INSERT INTO grdb_migrations VALUES('v26-efficiency-heal');
INSERT INTO grdb_migrations VALUES('v27-ppg-waveform');
INSERT INTO grdb_migrations VALUES('v28-raw-imu');
INSERT INTO grdb_migrations VALUES('v29-score-input-provenance');
INSERT INTO grdb_migrations VALUES('v30-rr-ord');
INSERT INTO grdb_migrations VALUES('v31-deep-capture-channels');
INSERT INTO grdb_migrations VALUES('v32-rr-src-channel');
INSERT INTO grdb_migrations VALUES('v33-workout-steps');
INSERT INTO grdb_migrations VALUES('v34-sleep-staging-sparse');
INSERT INTO grdb_migrations VALUES('v35-rr-future-quarantine');
INSERT INTO grdb_migrations VALUES('v36-whoop-caps-no-spo2');
INSERT INTO grdb_migrations VALUES('v37-daily-avg-sdnn');
INSERT INTO grdb_migrations VALUES('v38-apple-step-hour');
INSERT INTO grdb_migrations VALUES('v39-ppg-burst-index');
INSERT INTO grdb_migrations VALUES('v40-daily-skin-temp-absolute');
INSERT INTO grdb_migrations VALUES('v41-drop-raw-imu-sample');
INSERT INTO grdb_migrations VALUES('v42-daily-sleep-hr-only');
INSERT INTO grdb_migrations VALUES('v43-coach-messages');
INSERT INTO grdb_migrations VALUES('v44-ppg-waveform-base-code');
CREATE TABLE IF NOT EXISTS "device" ("id" TEXT PRIMARY KEY, "mac" TEXT, "name" TEXT, "firstSeen" INTEGER, "lastSeen" INTEGER);
CREATE TABLE IF NOT EXISTS "hrSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "bpm" INTEGER NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("deviceId", "ts"));
INSERT INTO hrSample VALUES('my-whoop',1780000000,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000001,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000002,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000003,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000004,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000005,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000006,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000007,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000008,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000009,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000010,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000011,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000012,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000013,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000014,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000015,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000016,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000017,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000018,60,0);
INSERT INTO hrSample VALUES('my-whoop',1780000019,60,0);
CREATE TABLE IF NOT EXISTS "event" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "kind" TEXT NOT NULL, "payloadJSON" TEXT NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("deviceId", "ts", "kind"));
CREATE TABLE IF NOT EXISTS "battery" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "soc" DOUBLE, "mv" INTEGER, "synced" INTEGER NOT NULL DEFAULT 0, "charging" BOOLEAN, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "rawBatch" ("batchId" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL, "capturedAt" INTEGER NOT NULL, "deviceClockRef" INTEGER NOT NULL, "wallClockRef" INTEGER NOT NULL, "startTs" INTEGER NOT NULL, "endTs" INTEGER NOT NULL, "frameCount" INTEGER NOT NULL, "byteSize" INTEGER NOT NULL, "framesBlob" BLOB NOT NULL, "syncedAt" INTEGER);
CREATE TABLE IF NOT EXISTS "cursors" ("name" TEXT PRIMARY KEY, "value" INTEGER);
CREATE TABLE IF NOT EXISTS "spo2Sample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "red" INTEGER NOT NULL, "ir" INTEGER NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "skinTempSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "raw" INTEGER NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, "aux1Raw" INTEGER, "aux2Raw" INTEGER, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "respSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "raw" INTEGER NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "gravitySample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "x" DOUBLE NOT NULL, "y" DOUBLE NOT NULL, "z" DOUBLE NOT NULL, "synced" INTEGER NOT NULL DEFAULT 0, "dynAccel" DOUBLE, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "sleepSession" ("deviceId" TEXT NOT NULL, "startTs" INTEGER NOT NULL, "endTs" INTEGER NOT NULL, "efficiency" DOUBLE, "restingHr" INTEGER, "avgHrv" DOUBLE, "stagesJSON" TEXT, "userEdited" BOOLEAN NOT NULL DEFAULT 0, "startTsAdjusted" INTEGER, "motionJSON" TEXT, "sleepStateJSON" TEXT, "stagingSparse" INTEGER, PRIMARY KEY ("deviceId", "startTs"));
CREATE TABLE IF NOT EXISTS "dailyMetric" ("deviceId" TEXT NOT NULL, "day" TEXT NOT NULL, "totalSleepMin" DOUBLE, "efficiency" DOUBLE, "deepMin" DOUBLE, "remMin" DOUBLE, "lightMin" DOUBLE, "disturbances" INTEGER, "restingHr" INTEGER, "avgHrv" DOUBLE, "recovery" DOUBLE, "strain" DOUBLE, "exerciseCount" INTEGER, "spo2Pct" DOUBLE, "skinTempDevC" DOUBLE, "respRateBpm" DOUBLE, "steps" INTEGER, "activeKcalEst" DOUBLE, "spo2Red" INTEGER, "spo2Ir" INTEGER, "avgSdnn" DOUBLE, "skinTempC" DOUBLE, "sleepHrOnly" BOOLEAN, PRIMARY KEY ("deviceId", "day"));
INSERT INTO dailyMetric VALUES('my-whoop-noop','2026-06-01',420.0,0.9,80.0,90.0,250.0,2,55,48.5,71.0,9.0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "journal" ("deviceId" TEXT NOT NULL, "day" TEXT NOT NULL, "question" TEXT NOT NULL, "answeredYes" INTEGER NOT NULL, "notes" TEXT, "numericValue" DOUBLE, PRIMARY KEY ("deviceId", "day", "question"));
CREATE TABLE IF NOT EXISTS "workout" ("deviceId" TEXT NOT NULL, "startTs" INTEGER NOT NULL, "endTs" INTEGER NOT NULL, "sport" TEXT NOT NULL, "source" TEXT NOT NULL, "durationS" DOUBLE, "energyKcal" DOUBLE, "avgHr" INTEGER, "maxHr" INTEGER, "strain" DOUBLE, "distanceM" DOUBLE, "zonesJSON" TEXT, "notes" TEXT, "steps" INTEGER, PRIMARY KEY ("deviceId", "startTs", "sport"));
CREATE TABLE IF NOT EXISTS "appleDaily" ("deviceId" TEXT NOT NULL, "day" TEXT NOT NULL, "steps" INTEGER, "activeKcal" DOUBLE, "basalKcal" DOUBLE, "vo2max" DOUBLE, "avgHr" INTEGER, "maxHr" INTEGER, "walkingHr" INTEGER, "weightKg" DOUBLE, PRIMARY KEY ("deviceId", "day"));
CREATE TABLE IF NOT EXISTS "metricSeries" ("deviceId" TEXT NOT NULL, "day" TEXT NOT NULL, "key" TEXT NOT NULL, "value" DOUBLE NOT NULL, PRIMARY KEY ("deviceId", "day", "key"));
CREATE TABLE IF NOT EXISTS "stepSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "counter" INTEGER NOT NULL, "activityClass" INTEGER, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "ppgHrSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "bpm" DOUBLE NOT NULL, "conf" DOUBLE NOT NULL, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE pairedDevice (
        id TEXT PRIMARY KEY NOT NULL,
        brand TEXT NOT NULL, model TEXT NOT NULL, nickname TEXT,
        sourceKind TEXT NOT NULL, capabilities TEXT NOT NULL,  -- comma-joined Metric rawValues
        status TEXT NOT NULL, addedAt INTEGER NOT NULL, lastSeenAt INTEGER NOT NULL
    , peripheralId TEXT);
INSERT INTO pairedDevice VALUES('my-whoop','WHOOP','5.0 MG',NULL,'liveBLE','hr,hrv,skinTemp,sleep,strainLoad','active',1789625231,1789625231,NULL);
CREATE TABLE dayOwnership (
        day TEXT PRIMARY KEY NOT NULL,   -- "YYYY-MM-DD" local day
        deviceId TEXT NOT NULL,          -- which device owns this day's displayed/scored metrics
        locked INTEGER NOT NULL DEFAULT 0 -- 1 = explicit (import-overlap decision / user); 0 = resolver default
    );
CREATE TABLE IF NOT EXISTS "labMarker" ("id" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL, "markerKey" TEXT NOT NULL, "category" TEXT NOT NULL, "day" TEXT NOT NULL, "takenAt" INTEGER NOT NULL, "value" DOUBLE, "valueText" TEXT, "unit" TEXT NOT NULL, "source" TEXT NOT NULL, "note" TEXT, "referenceText" TEXT);
CREATE TABLE IF NOT EXISTS "sleepStateSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "state" INTEGER NOT NULL, "rawByte" INTEGER, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "liveSession" ("deviceId" TEXT NOT NULL, "startTs" INTEGER NOT NULL, "endTs" INTEGER, "chargeAtStart" DOUBLE, "floorBpm" DOUBLE NOT NULL, "ceilingBpm" DOUBLE NOT NULL, "inBandSec" DOUBLE NOT NULL DEFAULT 0, "belowSec" DOUBLE NOT NULL DEFAULT 0, "aboveSec" DOUBLE NOT NULL DEFAULT 0, "pushCount" INTEGER NOT NULL DEFAULT 0, "easeCount" INTEGER NOT NULL DEFAULT 0, "hrSource" TEXT NOT NULL, PRIMARY KEY ("deviceId", "startTs"));
CREATE TABLE IF NOT EXISTS "rrInterval" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "rrMs" INTEGER NOT NULL, "seq" INTEGER NOT NULL DEFAULT 0, "synced" INTEGER NOT NULL DEFAULT 0, "ord" INTEGER, "srcChannel" INTEGER, "tsSuspect" INTEGER, PRIMARY KEY ("deviceId", "ts", "rrMs", "seq"));
INSERT INTO rrInterval VALUES('my-whoop',1780000000,1010,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000001,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000002,1010,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000003,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000004,1010,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000005,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000006,1010,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000007,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000008,1010,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000009,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000100,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000101,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000102,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000103,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000104,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000105,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000106,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000107,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000108,990,0,0,0,NULL,NULL);
INSERT INTO rrInterval VALUES('my-whoop',1780000109,990,0,0,0,NULL,NULL);
CREATE TABLE IF NOT EXISTS "ouraRaw" ("deviceId" TEXT NOT NULL, "endpoint" TEXT NOT NULL, "documentId" TEXT NOT NULL, "day" TEXT, "payloadJSON" TEXT NOT NULL, "fetchedAt" INTEGER NOT NULL, PRIMARY KEY ("deviceId", "endpoint", "documentId"));
CREATE TABLE IF NOT EXISTS "ppgWaveformSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "samples" BLOB NOT NULL, "burstIndex" INTEGER, "baseCode" INTEGER, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "scoreInputProvenance" ("deviceId" TEXT NOT NULL, "day" TEXT NOT NULL, "key" TEXT NOT NULL, "sourceId" TEXT NOT NULL, PRIMARY KEY ("deviceId", "day", "key"));
CREATE TABLE IF NOT EXISTS "v18AuxSample" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "fields" BLOB NOT NULL, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "appleStepHour" ("deviceId" TEXT NOT NULL, "ts" INTEGER NOT NULL, "steps" INTEGER NOT NULL, PRIMARY KEY ("deviceId", "ts"));
CREATE TABLE IF NOT EXISTS "coachMessage" ("id" TEXT PRIMARY KEY, "role" TEXT NOT NULL, "text" TEXT NOT NULL, "provider" TEXT NOT NULL, "createdAt" INTEGER NOT NULL, "orderIndex" INTEGER NOT NULL);
CREATE INDEX "idx_metricSeries_device_key_day" ON "metricSeries"("deviceId", "key", "day");
CREATE UNIQUE INDEX "idx_labMarker_natural" ON "labMarker"("deviceId", "markerKey", "takenAt", "source");
CREATE INDEX "idx_labMarker_device_marker_takenAt" ON "labMarker"("deviceId", "markerKey", "takenAt");
CREATE INDEX "idx_labMarker_device_category" ON "labMarker"("deviceId", "category");
CREATE INDEX "idx_ouraRaw_device_endpoint_day" ON "ouraRaw"("deviceId", "endpoint", "day");
CREATE INDEX "idx_scoreInputProvenance_source" ON "scoreInputProvenance"("sourceId");
COMMIT;
