import WidgetKit
import SwiftUI

/// The widget extension entry point. Bundles the glanceable widget, the three-rings widget
/// (redesign §9), the energy widget, the live-HR Live Activity and the heart-rate trace widget (#1957).
///
/// `CoachBriefWidget` is deliberately NOT registered yet: it renders whatever `CoachBriefScheduler`
/// last stored, and this fork's brief is generated by `AICoachEngine.startBriefIfNeeded` on its own
/// gate. Registering it before that wiring exists would ship a widget that can only say "nothing yet".
@main
struct NOOPWidgetBundle: WidgetBundle {
    var body: some Widget {
        NOOPWidget()
        NOOPRingsWidget()
        NOOPEnergyWidget()
        NOOPLiveActivity()
        HeartRateWidget()
    }
}
